version: '3'
services:
  eureka-server:
    build:
      context: ./
      dockerfile: Dockerfile-eureka
    restart: always
    ports:
      - 1000:1000

  config-server:
    links:
      - eureka-server:eureka
    build:
      context: ./
      dockerfile: Dockerfile-config
    restart: always
    ports:
      - 1002:1002

  auth-server:
    links:
      - eureka-server:eureka
    build:
      context: ./
      dockerfile: Dockerfile-auth
    restart: always
    ports:
      - 1004:1004
    volumes:
      - /usr/web/logs/auth/:/usr/web/logs/auth/
      - /etc/localtime/:/etc/localtime/

  admin-server:
    links:
      - eureka-server:eureka
    build:
      context: ./
      dockerfile: Dockerfile-admin
    restart: always
    ports:
      - 2002:2002
    volumes:
      - /usr/web/logs/admin/:/usr/web/logs/admin/
      - /etc/localtime/:/etc/localtime/

  pay-server:
    links:
      - eureka-server:eureka
    build:
      context: ./
      dockerfile: Dockerfile-pay
    restart: always
    ports:
      - 2003:2003
    volumes:
      - /usr/web/logs/pay/:/usr/web/logs/pay/
      - /usr/web/cert/:/usr/web/cert/
      - /etc/localtime/:/etc/localtime/

  wechat-server:
    links:
      - eureka-server:eureka
    build:
      context: ./
      dockerfile: Dockerfile-wechat
    restart: always
    ports:
      - 2004:2004
    volumes:
      - /usr/web/logs/wechat/:/usr/web/logs/wechat/
      - /etc/localtime/:/etc/localtime/

  gateway-server:
    links:
      - eureka-server:eureka
      - auth-server:auth
      - admin-server:admin
      - pay-server:pay
      - wechat-server:wechat
    build:
      context: ./
      dockerfile: Dockerfile-gateway
    restart: always
    ports:
      - 1003:1003
    volumes:
      - /usr/web/logs/:/usr/web/logs/
      - /etc/localtime/:/etc/localtime/

